### ISSUE TITLE
Segfault when resizing OpenTK window to small size

### ISSUE THREAD

**Issue by Nebula-Developer** [Nebula-Developer/Natsu#1]
Occurs on latest beta NVIDIA drivers (565.57.01)
When resizing the openTK window to any small value (~<75) the window inconsistently crashes with a segfault originating from `libnvidia-glcore`.

gdb backtrace:
```
#0  0x00007fffed1bdb35 in ?? () from /usr/lib/libnvidia-glcore.so.565.57.01
#1  0x00007fffecbeabce in ?? () from /usr/lib/libnvidia-glcore.so.565.57.01
#2  0x00007fffecbed239 in ?? () from /usr/lib/libnvidia-glcore.so.565.57.01
#3  0x00007fffecbb15b3 in ?? () from /usr/lib/libnvidia-glcore.so.565.57.01
#4  0x00007fbf468f52f6 in ?? ()
   from /home/nebuladev/Documents/Natsu/Natsu.Sandbox/bin/Debug/net8.0/linux-x64/libSkiaSharp.so
#5  0x00007fbf466c2924 in ?? ()
   from /home/nebuladev/Documents/Natsu/Natsu.Sandbox/bin/Debug/net8.0/linux-x64/libSkiaSharp.so
```

A quick workaround is just to set the minimum client size to something realistic ((75,75) works fine).

**Comment by Nebula-Developer** [comment]
Realistically, applications will not ever utilize sizes that this bug affects, so this isn't high priority. I'll keep this open for now, and I'll spend some time investigating later.
